<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="keywords" content="joimfw,juanma,serrano" />
<meta name="author" content="Juan Manuel Serrano" />
<meta name="publisher" content="Juan Manuel Serrano" />
<meta name="copyright" content="Juan Manuel Serrano, 2013" />
<meta name="language" content="en_EN" />
<meta name="description" content="Page description." />
<title>Base HTML template for the webpage</title>
<link href="/css/main.css" rel="stylesheet" type="text/css"></link>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<link rel="icon" type="image/x-icon" href="/favicon.png" />
<!-- You might add JS here, like jQuery -->
</head>

<body>
<!-- Header -->
<div class='maintitle clear0' id='title'><h1><a href='/'>Web title</a></h1></div>
<!-- Contenido -->
<div id='wrap' class='wrapper'>
	<div class='content'>
		<table id='wrapper'>
			<tbody>
			<tr>
				<td style='vertical-align:top; padding-right: 5px;'>
				<!-- Menu -->
					<dl>
						<dt>Menu title</dt>
						<dd><a href='/'>Home</a></dd>
					</dl>
				</td>
				<td> <!-- Contents -->
					{content}
				</td>
			</tr>
			</tbody>
		</table>
	</div>
</div>

<!-- Pie -->
<div id='foot' class='footer'>
	This is a footer.<br />
	&copy;2013 Juanma Serrano &bull; Website powered by <strong>JoimFW</strong>
</div>
</body>
</html>
