<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="keywords" content="joim,framework" />
<meta name="author" content="Juan Manuel Serrano" />
<meta name="publisher" content="Juan Manuel Serrano" />
<meta name="copyright" content="Juan Manuel Serrano, 2013" />
<meta name="language" content="en_EN" />
<meta name="description" content="Page description." />
<title>JoimFW</title>
<link href="/front/css/main.css" rel="stylesheet" type="text/css"></link>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.png" />
<link rel="icon" type="image/x-icon" href="/favicon.png" />
<link rel="stylesheet" href="/css/font-awesome.min.css">
<!--[if IE 7]>
  <link rel="stylesheet" href="/css/font-awesome-ie7.min.css">
<![endif]-->
<script type="text/javascript" src="/js/jquery-2.0.2.min.js"></script>
{js}</head>