<div style='margin: 0 auto;'>
Bienvenidos a <strong>Pokemaestro</strong>, hogar de los usuarios de TQD jugadores de Pokémon competitivo.<br />
Esta página ha sido creada con fin de servir como plataforma para diversos torneos, como los <strong>Torneos de Pokémon de TQD</strong>, también contamos con un poco de información y links a páginas útiles como <a href='http://www.smogon.com'>Smogon</a>.<br />
</div>